name: Get Livescores

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
    - cron: "*/5 6-22 * * *"
    - cron: "0 23 * * SUN"

env:
  BOT_TOKEN: "${{ secrets.TELEGRAM_BOT_TOKEN }}"
  CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"

jobs:
  getLiveScores:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Today Events
        if: github.event.schedule == '0 6 * * *' || github.event_name == 'workflow_dispatch'
        run: .\src\actions.ps1 -Action get-today-events
        shell: pwsh

      - name: Get Event Incidents
        run: .\src\actions.ps1 -Action get-event-incidents
        shell: pwsh

      - name: Install pnpm
        if: github.event.schedule == '0 23 * * SUN'
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install node.js 20.x
        if: github.event.schedule == '0 23 * * SUN'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Generate and send tables
        if: github.event.schedule == '0 23 * * SUN'
        run: .\src\actions.ps1 -Action send-league-tables
        shell: pwsh

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: GitHub Actions <actions@github.com>
